name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    # This will trigger the workflow for pull requests to any branch
    types: [opened, synchronize, reopened]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      
      - name: Set up Python 
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest -vs tests
